version: "3.8"
services:
  shell:
    build:
      context: ./mfe-shell
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    depends_on:
      - user
      - product
      - order

  product:
    build:
      context: ./mfe-product
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production

  order:
    build:
      context: ./mfe-order
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=production

  user:
    build:
      context: ./mfe-user
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      - NODE_ENV=production
